# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Firezone paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "{{ firezone_uid }}"
    group: "{{ firezone_gid }}"
  with_items:
    - "{{ firezone_base_path }}"
    - "{{ firezone_config_path }}"

- name: Ensure Firezone data path exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
    owner: "{{ firezone_uid }}"
    group: "{{ firezone_gid }}"
  with_items:
    - "{{ firezone_data_path }}"

- name: Ensure Firezone support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ firezone_config_path }}/{{ item }}"
    owner: "{{ firezone_uid }}"
    group: "{{ firezone_gid }}"
    mode: "0640"
  with_items:
    - env
    - labels

- name: Ensure Firezone container image is pulled is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ firezone_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Firezone container image is pulled via command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ firezone_container_image }}"
  register: result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: result is not failed

- name: Ensure Firezone container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ firezone_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure Firezone container network exists via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ firezone_container_network }}
  register: network_creation_result
  failed_when: network_creation_result.rc != 0 and 'already exists' not in network_creation_result.stderr

- name: Ensure Firezone systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/firezone.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ firezone_identifier }}.service"
    mode: "0644"
