---

- name: Ensure Firezone network is created in Docker
  community.docker.docker_network:
    name: "{{ firezone_container_network }}"
    driver: bridge


- name: Ensure Firezone path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ firezone_uid }}"
    group: "{{ firezone_gid }}"
  with_items:
    - {path: "{{ firezone_base_path }}", when: true}
    - {path: "{{ firezone_config_path }}", when: true}
    - {path: "{{ firezone_data_path }}", when: true}


- name: Ensure Firezone traefik labels are installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/labels.j2"
    dest: "{{ firezone_config_path }}/labels"
    owner: "{{ firezone_uid }}"
    group: "{{ firezone_gid }}"
    mode: 0640
  when: "firezone_playbook_traefik_role_enabled"

- name: Ensure firezone node configuration is deployed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/env.j2"
    dest: "{{ firezone_config_path }}/env"
    owner: "{{ firezone_uid }}"
    group: "{{ firezone_gid }}"
    mode: 0640

- name: Ensure Firezone container image is pulled
  community.docker.docker_image:
    name: "{{ firezone_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"

- name: Ensure firezone.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/firezone.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ firezone_identifier }}.service"
    mode: 0644
